services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_quite_path
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-quite_path}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT:-0001}:0002"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/migrations:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-jiragram_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postgres_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadminQuitePath
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "${PGADMIN_PORT:-0003}:0004" 
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  postgres_network:
    name: postgres_network